### ISSUE TITLE
Error in example command

### ISSUE THREAD

**Issue by jnarita** [Nickpizzablock/bwamin#1]
Hey @Nickpizzablock , I was reviewing your code for CSE185 and found there to be an issue with the example command. When I run it, it gives me an error on Line 44. When I add the "--mem" option, I get an error from pyfaidx on line 69

**Comment by Nickpizzablock** [comment]
Hi. Can you reply with the text when doing 'git log' on the console so I can see which version you have? I forgot to push my changes, so it should be fixed in the most resent version.

**Comment by jnarita** [comment]
@Nickpizzablock I didn't pull the repository, I just downloaded the code as a zip and then extracted and ran it. I still get an error on line 44 as of downloading at 8:02am may 31

**Comment by Nickpizzablock** [comment]
@jnarita Oh, my example code was wrong. You need to have either `--index` or `--mem` for the option. I updated the sample code which should work.

**Comment by jnarita** [comment]
Cool @Nickpizzablock it says now 
```shell
bwamin-main$ python3 bwamin.py --mem testfastring.fa testfqstring.fq
there is a match
hellowaorld
```
